### ISSUE TITLE
Bio Page - Jose Celano

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-website-v1#100]
Relates to: https://github.com/torrust/torrust-website/discussions/96

Info from https://github.com/josecelano

Articles:

- Containerizing Rust Applications with @da2ce7 
- [Introducing the New Sample Torrent Migration Tool](https://torrust.com/introducing-the-new-sample-torrent-migration-tool)
- [The Enigmatic Torrent "Source" Field](https://torrust.com/the-enigmatic-torrent-source-field)
- [How To Run A Local Demo](https://torrust.com/how-to-run-a-local-demo)
- [How To Setup The Dev Env](https://torrust.com/how-to-setup-the-development-environment)

**Comment by josecelano** [comment]
Hi @grmbyrn I've added the list of articles I've written. The last one (Containerizing Rust Applications) is not published yet. I will probably publish it today. I did it together with @da2ce7 since we was who did the current container configuration.

**Comment by grmbyrn** [comment]
Thanks, Jose! I've linked your author page to each of these.

**Comment by josecelano** [comment]
Close via https://github.com/torrust/torrust-website/pull/111.
