### ISSUE TITLE
Bio Page -  Cameron Garnham

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-website-v1#101]
Relates to: https://github.com/torrust/torrust-website/discussions/96

**Comment by da2ce7** [comment]
Cameron Garnham is a Supporter of Open Source Software and has many years of experience in information technologies. Mostly self-taught over the years, has focused on computer software architecture, system security, software engineering principles and processes, and practical cryptography and associated block chain technologies.

Now Cameron is mostly focused on human relations, hiring, and cooperate strategic vision and planning. He lends his focus to Nautilus and therefore the Torrust Project as he finds the technology interesting, and considers the core team his friends.

**Comment by cgbosse** [comment]
Nice Bio text.

**Comment by josecelano** [comment]
Close via https://github.com/torrust/torrust-website/pull/111.
