### ISSUE TITLE
Bio Page -  Warm Beer

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-website-v1#105]

**Comment by cgbosse** [comment]
@WarmBeer with a pic of Lucky the Pirate!

**Comment by mickvandijke** [comment]
Hey @josecelano , Where should I add my bio page? I can't see any of the existing bio pages in the code.

**Comment by josecelano** [comment]
> Hey @josecelano , Where should I add my bio page? I can't see any of the existing bio pages in the code.

Hi, @grmbyrn is doing it. You can just write a comment here. Bio pages are still not merged. And there is no draft PR.

**Comment by mickvandijke** [comment]
Mick van Dijke is a fullstack software engineer from The Netherlands with a love for high performance and efficient software. My expertise is [Rust](https://www.rust-lang.org/) and [Vue](https://vuejs.org/)/[Node](https://nodejs.org/en/).

Besides being a developer, I am also very interested in investing and blockchain technology.

**Comment by grmbyrn** [comment]
Thanks, Mick! I'll add it and make the PR.

**Comment by cgbosse** [comment]
Third person in all the text.

**Comment by josecelano** [comment]
Close via https://github.com/torrust/torrust-website/pull/111.
