### ISSUE TITLE
Review article: How To Run A Local Demo

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-website-v1#114]
Relates to: https://github.com/torrust/torrust-compose/issues/3

There have been containers changes.

**Comment by cgbosse** [comment]
@josecelano 
What do you expect to be done here? 
You want us to review the articles which are accessible through the link on top? This one: Relates to: https://github.com/torrust/torrust-compose/issues/3

**Comment by josecelano** [comment]
> @josecelano 
> What do you expect to be done here? 
> You want us to review the articles which are accessible through the link on top? This one: Relates to: https://github.com/torrust/torrust-compose/issues/3
> 

Hi @cgbosse just check if it still works. I don't think so, a lot of things have changed.

**Comment by josecelano** [comment]
[Tracker env vars have been renamed](https://github.com/torrust/torrust-index/issues/576):

```
TORRUST_TRACKER_DATABASE_DRIVER -> TORRUST_TRACKER_CONFIG_OVERRIDE_DB_DRIVER
TORRUST_TRACKER_API_ADMIN_TOKEN -> TORRUST_TRACKER_CONFIG_OVERRIDE_HTTP_API__ACCESS_TOKENS__ADMIN

TORRUST_TRACKER_CONFIG          -> TORRUST_TRACKER_CONFIG_TOML
TORRUST_TRACKER_PATH_CONFIG     -> TORRUST_TRACKER_CONFIG_TOML_PATH
```

**Comment by josecelano** [comment]
Closed via https://github.com/torrust/torrust-website/pull/188
