### ISSUE TITLE
Review article: How To Setup The Dev Env

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-website-v1#121]
There has been some changes:

- Repositories were renamed.
- Enva vars like `TORRUST_IDX_BACK_CORS_PERMISSIVE` were also renamed.
- Etc.

**Comment by cgbosse** [comment]
@josecelano 
What do you expect to be done here?

**Comment by josecelano** [comment]
Close via https://github.com/torrust/torrust-website/pull/165

**Comment by josecelano** [comment]
[Tracker env vars have been renamed](https://github.com/torrust/torrust-index/issues/576):

```
TORRUST_TRACKER_DATABASE_DRIVER -> TORRUST_TRACKER_CONFIG_OVERRIDE_DB_DRIVER
TORRUST_TRACKER_API_ADMIN_TOKEN -> TORRUST_TRACKER_CONFIG_OVERRIDE_HTTP_API__ACCESS_TOKENS__ADMIN

TORRUST_TRACKER_CONFIG          -> TORRUST_TRACKER_CONFIG_TOML
TORRUST_TRACKER_PATH_CONFIG     -> TORRUST_TRACKER_CONFIG_TOML_PATH
```
