### ISSUE TITLE
Add Live Demo button to Hero section

### ISSUE THREAD

**Issue by grmbyrn** [torrust/torrust-website-v1#135]
Add a button to the hero which leads to the [live demo](https://index.torrust-demo.com/torrents), as in the image below:

<img width="1112" alt="Screenshot 2024-01-25 at 16 54 49" src="https://github.com/torrust/torrust-website/assets/95353365/a3af55a5-5182-4401-84a2-c1145c75cc96">

**Comment by josecelano** [comment]
https://github.com/torrust/torrust-website/pull/136
