### ISSUE TITLE
Missing components in the storybook

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-website-v1#169]
Missing components:

- Image
- RssLink
- ShareButton
- SingleSparkle
- Strap
- ContributorCard
- PostBody
- PostContainer
- PostTable
- ThemeToggle
- AboutTorrust
- Features
- Footer
- HowToContribute
- RecentPosts
- RelatedPosts

All components:

```
src/lib/components/
├── atoms
│   ├── AnimatedHamburger.story.svelte
│   ├── AnimatedHamburger.svelte
│   ├── Button.story.svelte
│   ├── Button.svelte
│   ├── Card.story.svelte
│   ├── Card.svelte
│   ├── Image.svelte
│   ├── Logo.story.svelte
│   ├── Logo.svelte
│   ├── RssLink.svelte
│   ├── ShareButton.svelte
│   ├── SingleSparkle.svelte
│   ├── Sparkles.story.svelte
│   ├── Sparkles.svelte
│   ├── Strap.svelte
│   ├── Tag.story.svelte
│   └── Tag.svelte
├── molecules
│   ├── BlogPostCard.story.svelte
│   ├── BlogPostCard.svelte
│   ├── Callout.story.svelte
│   ├── Callout.svelte
│   ├── CodeBlock.story.svelte
│   ├── CodeBlock.svelte
│   ├── ContributionCard.story.svelte
│   ├── ContributionCard.svelte
│   ├── ContributorCard.svelte
│   ├── FeatureCard.story.svelte
│   ├── FeatureCard.svelte
│   ├── MarkerHighlight.story.svelte
│   ├── MarkerHighlight.svelte
│   ├── PostBody.svelte
│   ├── PostContainer.svelte
│   ├── PostTable.svelte
│   ├── ProjectCard.story.svelte
│   ├── ProjectCard.svelte
│   ├── Socials.story.svelte
│   ├── Socials.svelte
│   ├── SparklingHighlight.story.svelte
│   ├── SparklingHighlight.svelte
│   ├── ThemeToggle.svelte
│   ├── TintHighlight.story.svelte
│   └── TintHighlight.svelte
└── organisms
    ├── AboutTorrust.svelte
    ├── ContentSection.story.svelte
    ├── ContentSection.svelte
    ├── Features.svelte
    ├── Footer.svelte
    ├── Header.story.svelte
    ├── Header.svelte
    ├── Hero.story.svelte
    ├── Hero.svelte
    ├── HowToContribute.svelte
    ├── ImageContentSection.story.svelte
    ├── ImageContentSection.svelte
    ├── RecentPosts.svelte
    ├── RelatedPosts.svelte
    ├── Waves.story.svelte
    └── Waves.svelte
```

Storybook:

![image](https://github.com/torrust/torrust-website/assets/58816/a68ee188-410f-4c2c-b2ea-7a90446829d4)

Maybe we don't want to include them in the storybook because they are too specific? @grmbyrn @mario-nt?

**Comment by grmbyrn** [comment]
> Missing components:
> 
> * Image
> * RssLink
> * ShareButton
> * SingleSparkle
> * Strap
> * ContributorCard
> * PostBody
> * PostContainer
> * PostTable
> * ThemeToggle
> * AboutTorrust
> * Features
> * Footer
> * HowToContribute
> * RecentPosts
> * RelatedPosts
> 
> All components:
> 
> ```
> src/lib/components/
> ├── atoms
> │   ├── AnimatedHamburger.story.svelte
> │   ├── AnimatedHamburger.svelte
> │   ├── Button.story.svelte
> │   ├── Button.svelte
> │   ├── Card.story.svelte
> │   ├── Card.svelte
> │   ├── Image.svelte
> │   ├── Logo.story.svelte
> │   ├── Logo.svelte
> │   ├── RssLink.svelte
> │   ├── ShareButton.svelte
> │   ├── SingleSparkle.svelte
> │   ├── Sparkles.story.svelte
> │   ├── Sparkles.svelte
> │   ├── Strap.svelte
> │   ├── Tag.story.svelte
> │   └── Tag.svelte
> ├── molecules
> │   ├── BlogPostCard.story.svelte
> │   ├── BlogPostCard.svelte
> │   ├── Callout.story.svelte
> │   ├── Callout.svelte
> │   ├── CodeBlock.story.svelte
> │   ├── CodeBlock.svelte
> │   ├── ContributionCard.story.svelte
> │   ├── ContributionCard.svelte
> │   ├── ContributorCard.svelte
> │   ├── FeatureCard.story.svelte
> │   ├── FeatureCard.svelte
> │   ├── MarkerHighlight.story.svelte
> │   ├── MarkerHighlight.svelte
> │   ├── PostBody.svelte
> │   ├── PostContainer.svelte
> │   ├── PostTable.svelte
> │   ├── ProjectCard.story.svelte
> │   ├── ProjectCard.svelte
> │   ├── Socials.story.svelte
> │   ├── Socials.svelte
> │   ├── SparklingHighlight.story.svelte
> │   ├── SparklingHighlight.svelte
> │   ├── ThemeToggle.svelte
> │   ├── TintHighlight.story.svelte
> │   └── TintHighlight.svelte
> └── organisms
>     ├── AboutTorrust.svelte
>     ├── ContentSection.story.svelte
>     ├── ContentSection.svelte
>     ├── Features.svelte
>     ├── Footer.svelte
>     ├── Header.story.svelte
>     ├── Header.svelte
>     ├── Hero.story.svelte
>     ├── Hero.svelte
>     ├── HowToContribute.svelte
>     ├── ImageContentSection.story.svelte
>     ├── ImageContentSection.svelte
>     ├── RecentPosts.svelte
>     ├── RelatedPosts.svelte
>     ├── Waves.story.svelte
>     └── Waves.svelte
> ```
> 
> Storybook:
> 
> ![image](https://private-user-images.githubusercontent.com/58816/326716997-a68ee188-410f-4c2c-b2ea-7a90446829d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0NjQ4MjgsIm5iZiI6MTcxNDQ2NDUyOCwicGF0aCI6Ii81ODgxNi8zMjY3MTY5OTctYTY4ZWUxODgtNDEwZi00YzJjLWIyZWEtN2E5MDQ0NjgyOWQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDMwVDA4MDg0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4ZDA4YTA5MzY5N2FhODNiZjhiZWRjM2VhNzA0OTI3YWUwMmRhMmE3NmZhN2VkNTVkOTE0ZGQxZTE1ZWU4MzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.t4h__3warjLRYGRat5MZlfg1zPU0yEyoaCUidUP6_qk)
> 
> Maybe we don't want to include them in the storybook because they are too specific? @grmbyrn @mario-nt?

Hi @josecelano @mario-nt I'm not sure whether these components shouldn't have a storybook because they are too specific, but if it's the case that you would like to keep them consistent with the other components, I can add a storybook for each.

**Comment by josecelano** [comment]
Hi @grmbyrn, I think we should create a new folder for non-reusable components. Maybe we can call it "singletons." As soon as we have two instances, we should extract the common part into an atom, molecule, or organism. All atoms, molecules, or organisms should have a "*.story.svelte" file.

**Comment by grmbyrn** [comment]
> Hi @grmbyrn, I think we should create a new folder for non-reusable components. Maybe we can call it "singletons." As soon as we have two instances, we should extract the common part into an atom, molecule, or organism. All atoms, molecules, or organisms should have a "*.story.svelte" file.

Hi @josecelano I like this idea. ~~Do 'singletons' require a storybook or would you prefer to only give a storybook to them once they become atoms, molecules, or organisms?~~ I just saw your comment [here](https://github.com/torrust/torrust-website/pull/172#event-12682635938). I will remove the storybooks from the 'singletons' that are not reusable components.
