### ISSUE TITLE
Prev / Next blog posts at the bottom of blog posts

### ISSUE THREAD

**Issue by grmbyrn** [torrust/torrust-website-v1#179]
I think that a component like the example in the image below between the end of each blog post and the `RelatedPosts` component showing the next and previous blog posts would be a good addition. It would let the user know that each blog post is related and make it easier to navigate from one to the next.

<img width="1199" alt="Screenshot 2024-05-20 at 11 53 16" src="https://github.com/torrust/torrust-website/assets/95353365/20580010-5c65-4785-809e-3e49e5e49a54">

**Comment by josecelano** [comment]
Hi @grmbyrn I think it's a good idea. I will tell the designer who is working on the new design.
