### ISSUE TITLE
Rephrase tagline: Modern and Private BitTorrent Index and Tracker

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-website-v1#201]
![image](https://github.com/torrust/torrust-website/assets/58816/2c1e81da-a798-47c5-92b9-98431c244a0a)

The Tracker can be in full private mode but the [Index can't](https://github.com/torrust/torrust-index/discussions/431).

### Alternatives

- Modern BitTorrent Index and Tracker
- Modern BitTorrent Index and [private] Tracker

cc @torrust/torrustaceans

**Comment by mario-nt** [comment]
@josecelano I would use the first proposal (Modern BitTorrent Index and Tracker), and then, in the details, let the user know the tracker does have full private support and the index does not.

**Comment by josecelano** [comment]
> @josecelano I would use the first proposal (Modern BitTorrent Index and Tracker), and then, in the details, let the user know the tracker does have full private support and the index does not.

I agree. Ideally, we should support any type.
