### ISSUE TITLE
V2 - Index page - review and comments

### ISSUE THREAD

**Issue by cgbosse** [torrust/torrust-website-v1#221]
Link to page: <https://torrust.com/v2/index>

**Comment by cgbosse** [comment]
![image](https://github.com/user-attachments/assets/7d61640d-532a-4a9b-bea6-7187a5c4c404)

To do:
- Decide on the text to put instead of Lorem Ipsum
- Insert the links in the individual boxes text such as shown in the Miro board, see the image.
![image](https://github.com/user-attachments/assets/c601574c-b5fd-4b65-aad6-e4156645d9af)

Link to the miro board with the links box:  <https://miro.com/app/board/uXjVN7YuMmY=/?moveToWidget=3458764583505355230&cot=14>

**Comment by cgbosse** [comment]
![image](https://github.com/user-attachments/assets/c57d3c09-e229-41b8-9287-fb2b156ad6ad)


To do:
- Decide on the text to put instead of Lorem Ipsum
- Insert the links in the individual boxes text such as shown in the Miro board, see the image.

![image](https://github.com/user-attachments/assets/53934c6c-69a5-460a-8a2f-cd65e4c7d30a)


Link to the miro board with the links box:
https://miro.com/app/board/uXjVN7YuMmY=/?moveToWidget=3458764583587358355&cot=14

**Comment by cgbosse** [comment]
![image](https://github.com/user-attachments/assets/0c4f82c7-22b5-4d86-945c-cae256858c89)


To do:
- Decide on the text to put instead of Lorem Ipsum
- See the contents of the table with @josecelano

**Comment by cgbosse** [comment]
![image](https://github.com/user-attachments/assets/b2e1526d-9bd1-4b71-a540-9c368f2ff6f4)

I do not think that the "+"  for display adds much for usability since the contents is already reduced.

![image](https://github.com/user-attachments/assets/1b148bcb-4de7-4023-b53d-0666bafc1fa1)

I would try to emulate what Fer has in his template. What do you think @josecelano 

I say this because I think that the flow is that when going to for example the Licenses Link then it switches  the entire bottom part to that section, which is why he has in the corner the "Next:Licenses"

 
![image](https://github.com/user-attachments/assets/b4dc0039-0795-4f51-8ec9-15b5b13db1ca)

**Comment by cgbosse** [comment]
![image](https://github.com/user-attachments/assets/e010bb0e-19c3-48c3-9e0d-8b055d757b51)

Here it looks all good  to me.

**Comment by cgbosse** [comment]
![image](https://github.com/user-attachments/assets/b6234ac7-0dc1-42aa-8ce7-941de92ae974)



The entire text from the Miro Roadmap seems to be included.
However, we may have to review this and update it or state that these are features that we are considering to develop, thought the order is still to be decided. What do you think @josecelano ? 
It may also be good to create such a road map in Github and include a link to it.

**Comment by grmbyrn** [comment]
> ![image](https://private-user-images.githubusercontent.com/15330600/355770203-b2e1526d-9bd1-4b71-a540-9c368f2ff6f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwNDg5OTYsIm5iZiI6MTcyMzA0ODY5NiwicGF0aCI6Ii8xNTMzMDYwMC8zNTU3NzAyMDMtYjJlMTUyNmQtOWJkMS00YjcxLWE1NDAtOWMzNjhmMmZmNmY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDE2MzgxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyMTE0MmRlYWUzM2NiYWYzYTQyM2YyMTEzYmY1N2NlMTM5ZWYzZGZiOTgzZWIxN2U1OWM2NjI5ZmYyMjA1YTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3bOZT7ZpVj2TSo7vcOHsP0wSIGf05X7gaDerZ8CoXgI)
> 
> I do not think that the "+" for display adds much for usability since the contents is already reduced.
> 
> ![image](https://private-user-images.githubusercontent.com/15330600/355770535-1b148bcb-4de7-4023-b53d-0666bafc1fa1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwNDg5OTYsIm5iZiI6MTcyMzA0ODY5NiwicGF0aCI6Ii8xNTMzMDYwMC8zNTU3NzA1MzUtMWIxNDhiY2ItNGRlNy00MDIzLWI1M2QtMDY2NmJhZmMxZmExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDE2MzgxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3NDUzYzkzYTk2YzNmNWIyZTJhN2M5ZTBiNDk0MjU5YmVkMGViZTY5NTM4NDBlODEzYWU3NGM2MGQ0NDVjZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ejwxH-9L941YvpOmmqvgIErD-giFI2BurwE38tY9KLo)
> 
> I would try to emulate what Fer has in his template. What do you think @josecelano
> 
> I say this because I think that the flow is that when going to for example the Licenses Link then it switches the entire bottom part to that section, which is why he has in the corner the "Next:Licenses"
> 
> ![image](https://private-user-images.githubusercontent.com/15330600/355771928-b4dc0039-0795-4f51-8ec9-15b5b13db1ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwNDg5OTYsIm5iZiI6MTcyMzA0ODY5NiwicGF0aCI6Ii8xNTMzMDYwMC8zNTU3NzE5MjgtYjRkYzAwMzktMDc5NS00ZjUxLThlYzktMTViNWIxM2RiMWNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDE2MzgxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzZmM3ZmJjYzMwYjA0OTFmNWNkM2EwYWIwNWEwNTZkZDk1ZjVlMDE4ZWViYjM3ZGUxNzFmMTU0NDY0Y2ZkYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.O-tVI_Oedg8BoeBKnGgKGgHsTqBPaBlpiB_b8qppD8Q)

I added this dropdown menu based on this comment from Fer in the Figma:

>This menu will probably be reworked for mobile and tablet. I think something that takes less space (e.g. a sticky dropdown) will work better on those devices.

I'm not sure if this is exactly what he was going for, but if the final design doesn't call for this kind of dropdown on the submenu then it can be easily removed/updated. However, the current styling for the navigation is coming from the `scss` which is applied in v1 as well and is being applied globally. Once the designer provides the styles, this can be modified easily according to what they suggest.

As for the "Next:Licenses" part, I discussed with @josecelano about keeping all the sections on the same page as it is now instead of clicking the link. However, I can change it so that only one section appears at a time and the user can click to a link like "Next:Licenses" to see previous and next sections, one at a time.
