### ISSUE TITLE
Blog post cards not using the same format

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-website-v1#40]
Hi @matfantinel , for some reason, after adding a second blog post, they are not shown in the same way.

![image](https://github.com/torrust/torrust-website/assets/58816/7a2e0d08-7aef-4f92-9ec5-2cfdd1619526)

**Comment by matfantinel** [comment]
@josecelano hmm, yeah, that blog page listing doesn't look great when there's only a few blog posts. I've been wanting to rewrite that for a while but haven't got to it yet.

You can try changing the CSS in `(waves)/blog/page.svelte`, removing the entire `@include for-tablet-landscape-up` block, and replacing `grid-template-columns: 1fr 1fr 1fr 1fr 1fr 1fr;` with `grid-template-columns: 1fr 1fr;`. I think it'll look better! If you want just one post per line (so both are displayed like the first one in your screenshot), just use one `1fr` instead.

Not sure if you know much about CSS Grid, but "fr" is short for "fraction". So `grid-template-columns: 1fr 1fr` means you're making the grid have 2 columns of the same size.

**Comment by josecelano** [comment]
Hi @matfantinel I've just realized it's the intended behavior. The first one takes the whole width, and it seems it uses two columns for the rest.

![image](https://github.com/torrust/torrust-website/assets/58816/d5613f9f-4b8e-44b5-a9b1-d4e866b8eeb5)

It's ok, it just looks weird with two articles, but I will write the third one soon.
