### ISSUE TITLE
Embedded commands on blog posts could have a small icon to copy the commands to the clipboard

### ISSUE THREAD

**Issue by mario-nt** [torrust/torrust-website-v1#75]
Blog posts that contain commands, could display a button to allow the user to copy the info to the clipboard and make the follow along installation process easier.

How it looks right now:

![image](https://github.com/torrust/torrust-website/assets/141633147/a5452087-c730-4c5e-bcc6-5c891e84fcf0)

**Comment by josecelano** [comment]
Hi @grmbyrn

When you run the story with: `npm run story:preview`

![image](https://github.com/torrust/torrust-website/assets/58816/0b5fc328-8717-45d2-a6e3-421a468aedd1)

It has the option to copy the "source" code. We are using https://histoire.dev/guide/
