### ISSUE TITLE
Orthographic errors in the Torrust Post: "The Enigmatic Torrent "Source" Field"

### ISSUE THREAD

**Issue by cgbosse** [torrust/torrust-website-v1#78]
I went over the [blogpost](https://torrust.com/the-enigmatic-torrent-source-field) and found few mistakes.

![image](https://github.com/torrust/torrust-website/assets/15330600/0239059d-b85c-408e-98a9-95e03d8aa895)

----

![image](https://github.com/torrust/torrust-website/assets/15330600/cdbe2f5e-ebd1-482b-ad5d-fa2b31620043)

----

**Comment by cgbosse** [comment]
PLease check whether I did this properly since I did a direct commit. 

https://github.com/torrust/torrust-website/tree/develop/src/routes/(blog-article)/the-enigmatic-torrent-source-field

**Comment by josecelano** [comment]
Fixed via https://github.com/torrust/torrust-website/commit/62354570e8d91a94e244516e00bf3e7810cae960
