### ISSUE TITLE
Add contact form to page for users to send message

### ISSUE THREAD

**Issue by grmbyrn** [torrust/torrust-website-v1#92]
We could have a form at the bottom of the home page for users to submit a message, along with their name and email address, if they have any questions about anything they've read on the Torrust website, on the blog, or in any of the featured repos. Will depend on where these messages go and who will respond.

**Comment by josecelano** [comment]
> We could have a form at the bottom of the home page for users to submit a message, along with their name and email address, if they have any questions about anything they've read on the Torrust website, on the blog, or in any of the featured repos. Will depend on where these messages go and who will respond.

Hi @grmbyrn I usually write a short message at the end of the blog post with links where people can contribute. If the question, contribution, or suggestion is public, they can use [GitHub discussions](https://github.com/torrust/torrust-website/discussions).

Maybe we could add that part in the template so we do not have to do it manually.


![image](https://github.com/torrust/torrust-website/assets/58816/97ac42b7-4399-43bb-9bff-28653c655be4)

For private things it might be interesting to have a contact page.

**Comment by grmbyrn** [comment]
@josecelano That's a good point that the links are there in the article. Would it be worth adding a link to GitHub discussions, or telling them to open an issue if they've any questions, to the How to Contribute section on the home page? A lot of people tend not to read the article to the bottom and might miss the link to where they could get help.

**Comment by josecelano** [comment]
> @josecelano That's a good point that the links are there in the article. Would it be worth adding a link to GitHub discussions, or telling them to open an issue if they've any questions, to the How to Contribute section on the home page? A lot of people tend not to read the article to the bottom and might miss the link to where they could get help.

Yes, @grmbyrn I think we can add whatever we consider could make people see this as a shared project. People can:

- Open PRs to update articles, especially if they are tutorials.
- Open discussions.
- Create new articles.
- Etcetera

And it's Ok to remind them so in the README, top or bottom parts of the articles, hot to contribute section, etcetera. I would not be worried about having that info duplicated across the website.

For some people it will be easier to just open an issue and other people might prefer open a PR.
