### ISSUE TITLE
Bio Page - Constantin Bosse

### ISSUE THREAD

**Issue by cgbosse** [torrust/torrust-website-v1#98]
Constantin’s background is in business. He is currently Nautilus Cyberneering SLU’s general manager and the Blockfinance company group’s expert in business operations. He has over 23 years of experience in different industries, companies, and roles. 

Given that he has worked as a consultant for many years, if somebody asks him what he does, he simply replies that he mostly helps with projects, usually creating, optimizing, or closing companies.  He is creative, pragmatic and honest and is centered on helping others. I you ask him about something he does not know he will tell you and either research it or look for someone who does.

Regarding his passions and what he loves to write about are business and technology for their potential and importance to create lasting change and value for society, but also values and ethics for their importance in organizations and society.

Lastly, since his involvement in Open-Source projects and his exposure to decentralized technologies he has become a strong advocate of their philosophy and values since these resonate with his own.

**Comment by cgbosse** [comment]
I cannot assign this issue to Graeme until he is an organization team member.
@josecelano could you please add the two new developers thank you.

**Comment by josecelano** [comment]
> I cannot assign this issue to Graeme until he is an organization team member. @josecelano could you please add the two new developers thank you.

I've sent them the invitations.

**Comment by josecelano** [comment]
Close via https://github.com/torrust/torrust-website/pull/111.
