### ISSUE TITLE
Bio Page - Mario Melchor

### ISSUE THREAD

**Issue by mario-nt** [torrust/torrust-website-v1#99]
I am a Full Stack developer from Spain currently developing in Rust and Nuxt working on the Open Source Torrust project for Nautilus Cyberneering.

I have been working in the IT Industry for different companies since 2019, taking part on different projects both as a developer and support specialist using a stack of different technologies (Java, Javascript, NodeJs, PL/SQL...).

An avid learner, on my free time you can find me doing anything from music to fishing.

Thanks for checking out my profile and feel free to contact me for if you have any questions!

**Comment by mario-nt** [comment]
@cgbosse @grmbyrn

**Comment by cgbosse** [comment]
Personally I think that we should use the third person since this is not a personal blog or website.
However we can decide on this as a team.

**Comment by mario-nt** [comment]
> Personally I think that we should use the third person since this is not a personal blog or website. However we can decide on this as a team.

For me either way is valid, I will write it again in third person and see how it looks. After some research on other websites, they indeed use the third person when referring to members.

**Comment by grmbyrn** [comment]
Thanks a lot for both bios! I added @josecelano bio just as it is in his GitHub profile, which is in the first person. I made a pull request with his info but it hasn't been accepted yet. I can amend it to the third person as well as both of yours if you prefer. I'd also go with the third person for the reason Constantin mentioned.

Also, would you be able to list which blog posts you were responsible for? I don't think I have this info and I need this to link the author with their respective post. Thanks!

**Comment by cgbosse** [comment]
I would change Jose Celano's Bio to third person for consistency.
What do you think @josecelano ?

**Comment by josecelano** [comment]
Close via https://github.com/torrust/torrust-website/pull/111.
